name: Post to Mastodon

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - name: Post to Mastodon
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          MASTODON_CLIENT_KEY: ${{ secrets.MASTODON_CLIENT_KEY }}
          MASTODON_CLIENT_SECRET: ${{ secrets.MASTODON_CLIENT_SECRET }}
        run: node post-nameday.js
